version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" 
    depends_on:
      - backend
    restart: unless-stopped
    networks: 
      - app-network
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_PROXY_TARGET=${VITE_PROXY_TARGET}

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3545:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - API_KEY=${API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks: 
      - app-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
    command: mongod --auth
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge