version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3545:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/newscoon
      - API_KEY=hackhathon-newscoon-2025
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped
